#!/bin/bash
# cc-notify — main notification script
# Usage:
#   arg mode:   notify.sh [--provider claude|codex] [--urgent] [--force] "title line" ["line 2" ...]
#   stdin mode: echo '{"session_id":"..."}' | notify.sh                       (Stop hook)
#
# Flags (any order, must precede content args):
#   --urgent  displays the sticky note in a bold red urgent theme to stand out from regular notifications
#   --force   bypass deduplication — always trigger the notification even if content is identical to last time
#   --provider claude|codex  namespace hook state and parse provider-specific hook JSON

# Resolve the install directory; all dependencies live here (self-locating)
SKILL_SCRIPTS="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BINARY="$SKILL_SCRIPTS/sticky-notify.app/Contents/MacOS/sticky-notify-app"
TIMESTAMP=$(date '+%H:%M:%S')

# Parse flags first so provider/session are available for logging and state paths.
PROVIDER="claude"
URGENT=0
FORCE=0
while true; do
    case "${1:-}" in
        --urgent) URGENT=1; shift ;;
        --force)  FORCE=1;  shift ;;
        --provider)
            PROVIDER="${2:-claude}"
            shift 2
            ;;
        --provider=*)
            PROVIDER="${1#--provider=}"
            shift
            ;;
        *) break ;;
    esac
done

case "$PROVIDER" in
    claude|codex) ;;
    *) PROVIDER="claude" ;;
esac

json_get_string() {
    _key="$1"
    printf '%s' "$HOOK_JSON" | sed -nE 's/.*"'"$_key"'"[[:space:]]*:[[:space:]]*"([^"]+)".*/\1/p' | head -n 1
}

# Always read session/cwd from hook JSON when stdin is piped.
HOOK_JSON=""
SESSION_SHORT=""
PROJECT_CWD=""
if [ ! -t 0 ]; then
    HOOK_JSON=$(cat)
    for _session_key in session_id sessionId turn_id turnId; do
        _session_value=$(json_get_string "$_session_key" 2>/dev/null || true)
        if [ -n "$_session_value" ]; then
            SESSION_SHORT=$(printf '%s' "$_session_value" | tr -cd '[:alnum:]' | cut -c 1-16)
            break
        fi
    done
    PROJECT_CWD=$(json_get_string cwd 2>/dev/null || true)
fi

SESSION_KEY="${SESSION_SHORT:-default}"
STATE_KEY="${PROVIDER}-${SESSION_KEY}"
PROJECT=$(basename "${PROJECT_CWD:-$(pwd)}")

# ── Logging ──────────────────────────────────────────────────────────────────
# Record every invocation to ~/.cc-notify/notify.log for debugging.
# Log entry is written as early as possible so even crashes leave a trace.
# Auto-rotate: when log exceeds ~512KB, rename to .log.1 (keep one backup).
LOG_FILE="$HOME/.cc-notify/notify.log"
mkdir -p "$(dirname "$LOG_FILE")" 2>/dev/null
if [ -f "$LOG_FILE" ]; then
    _sz=$(stat -f%z "$LOG_FILE" 2>/dev/null || echo 0)
    [ "$_sz" -gt 524288 ] 2>/dev/null && mv -f "$LOG_FILE" "${LOG_FILE}.1" 2>/dev/null
fi
_log() { printf '%s [%s] %s\n' "$(date '+%Y-%m-%d %H:%M:%S')" "${STATE_KEY:-?}" "$*" >> "$LOG_FILE" 2>/dev/null; }
_log "INVOKE args=[$*] pwd=$(pwd)"

# Load user config (env.sh generated by `ccn set`, exports CC_STICKY_NOTIFY_CLOSE_TIMEOUT etc.)
# shellcheck disable=SC1091
[ -f "$SKILL_SCRIPTS/env.sh" ] && source "$SKILL_SCRIPTS/env.sh"

_log "SESSION provider=$PROVIDER key=$SESSION_KEY urgent=$URGENT force=$FORCE mode=$([ $# -gt 0 ] && echo 'arg' || echo 'stdin')"

if [ $# -gt 0 ]; then
    # Arg mode: use provided text, append timestamp (Project appended after Source detection)
    LINES=("$@" "Time: $TIMESTAMP")
else
    # Stdin mode: Stop hook — show completion message
    if [ "$PROVIDER" = "codex" ]; then
        LINES=("Codex task completed" "Time: $TIMESTAMP")
    else
        LINES=("✅ Claude Code task completed" "Time: $TIMESTAMP")
    fi
fi

# One window per provider session — use STATE_KEY so cd mid-session doesn't change the path
# PROJECT is used for display only (updated on every notification)
TMP_DIR="/tmp/cc-notify"
mkdir -p "$TMP_DIR"
CONTENT_FILE="$TMP_DIR/${STATE_KEY}.txt"
PID_FILE="$TMP_DIR/${STATE_KEY}.pid"
FOCUS_FILE="$TMP_DIR/${STATE_KEY}.focus"

# Walk process tree (pure ps calls, fast, synchronous)
_pid=$$
_ancestors=""
for _i in 1 2 3 4 5 6 7 8 9 10 11 12; do
    _pid=$(ps -p "$_pid" -o ppid= 2>/dev/null | tr -d ' ')
    if [ -z "$_pid" ] || [ "$_pid" = "0" ] || [ "$_pid" = "1" ]; then break; fi
    _ancestors="${_ancestors:+$_ancestors,}$_pid"
done

# Detect parent GUI app and front window via System Events (synchronous single call)
SOURCE_APP=""
if [ -n "$_ancestors" ]; then
    _wf="${FOCUS_FILE%.focus}.window"
    _posf="${FOCUS_FILE%.focus}.pos"
    _result=$(osascript -e "tell application \"System Events\"
set pids to {$_ancestors}
repeat with p in pids
    try
        set proc to first application process whose unix id is p
        if (background only of proc) is false and (bundle identifier of proc) is not missing value then
            set _n to name of proc
            set _w to \"\"
            set _px to \"\"
            set _py to \"\"
            try
                -- Prefer the window whose title starts with the project name.
                -- This correctly identifies the target IDEA/editor window when
                -- multiple windows of the same app are open for different projects.
                set _proj to "$PROJECT"
                set _projLen to length of _proj
                set _matched to missing value
                try
                    repeat with _wi in (windows of proc)
                        try
                            set _wname to name of _wi
                            if _projLen > 0 and length of _wname >= _projLen and text 1 thru _projLen of _wname is equal to _proj then
                                set _matched to _wi
                                exit repeat
                            end if
                        end try
                    end repeat
                end try
                -- Fallback to front window when no project-name match found
                if _matched is missing value then
                    try
                        set _matched to front window of proc
                    end try
                end if
                if _matched is not missing value then
                    set _w to name of _matched
                    set _pos to position of _matched
                    set _px to (item 1 of _pos) as text
                    set _py to (item 2 of _pos) as text
                end if
            end try
            return _n & \"|\" & _w & \"|\" & _px & \",\" & _py
        end if
    end try
end repeat
end tell" 2>/dev/null)
    if [ -n "$_result" ]; then
        SOURCE_APP=$(printf '%s' "${_result%%|*}" | tr -d '\r\n')
        _rest="${_result#*|}"
        _win=$(printf '%s' "${_rest%%|*}" | tr -d '\r\n')
        _pos=$(printf '%s' "${_rest#*|}" | tr -d '\r\n')
        [ -n "$SOURCE_APP" ] && printf '%s\n' "$SOURCE_APP" > "$FOCUS_FILE"
        # Window title and position written only once (first notification wins):
        # Prevents later hooks (e.g. Stop) from overwriting the original target window
        # if the user has switched to a different window in the meantime.
        [ -n "$_win" ] && [ ! -f "$_wf" ] && printf '%s\n' "$_win" > "$_wf"
        [[ "$_pos" == *,* ]] && [ ! -f "$_posf" ] && printf '%s\n' "$_pos" > "$_posf"
        # Capture CGWindowID — unique per window, reliable for multi-window matching
        _widFile="$TMP_DIR/${STATE_KEY}.wid"
        if [ ! -f "$_widFile" ]; then
            # Prefer the window whose title starts with $PROJECT (handles multiple windows
            # of the same app open for different projects). Falls back to the frontmost window.
            _wid=$(osascript -l JavaScript -e "
ObjC.import('CoreGraphics');ObjC.import('Foundation');
var target='$SOURCE_APP'.toLowerCase();
var project='$(printf '%s' "$PROJECT" | sed "s/'/\\\\'/g")';
var cfArr=\$.CGWindowListCopyWindowInfo(1,0);
var nsArr=ObjC.castRefToObject(cfArr);var r='',fallback='';
for(var i=0;i<nsArr.count;i++){var info=nsArr.objectAtIndex(i);
var owner=ObjC.unwrap(info.objectForKey('kCGWindowOwnerName'));
if(owner&&owner.toLowerCase()===target&&ObjC.unwrap(info.objectForKey('kCGWindowLayer'))===0){
var wid=''+ObjC.unwrap(info.objectForKey('kCGWindowNumber'));
var name=ObjC.unwrap(info.objectForKey('kCGWindowName'))||'';
if(project&&(name===project||name.indexOf(project+' ')===0||name.indexOf(project+'\u2013')===0||name.indexOf(project+' \u2013')===0)){r=wid;break;}
if(!fallback){fallback=wid;}}}r||fallback;" 2>/dev/null)
            [ -n "$_wid" ] && printf '%s\n' "$_wid" > "$_widFile"
        fi
    fi
fi

# Append Source (Time → Source → Project order)
[ -n "$SOURCE_APP" ] && LINES+=("Source: $SOURCE_APP")
LINES+=("Project: $PROJECT")

# Dedup: compute content signature excluding the Time: line
SIG=""
for _line in "${LINES[@]}"; do
    [[ "$_line" == Time:* ]] && continue
    SIG="${SIG}${_line}\n"
done
LAST_SIG_FILE="$TMP_DIR/${STATE_KEY}.sig"
if [ "$FORCE" != "1" ]; then
    if [ -f "$LAST_SIG_FILE" ]; then
        PREV_SIG=$(cat "$LAST_SIG_FILE" 2>/dev/null)
        if [ "$PREV_SIG" = "$SIG" ]; then
            _log "DEDUP_SKIP sig unchanged"
            exit 0  # Same content as last notification, skip
        fi
    fi
fi
printf '%s' "$SIG" > "$LAST_SIG_FILE"
_log "CONTENT_WRITE urgent=$URGENT title=${LINES[0]}"

if [ "$URGENT" = "1" ]; then
    { printf '__URGENT__\n'; printf '%s\n' "${LINES[@]}"; } > "$CONTENT_FILE"
else
    printf '%s\n' "${LINES[@]}" > "$CONTENT_FILE"
fi

if [ -f "$PID_FILE" ]; then
    EXISTING_PID=$(cat "$PID_FILE" 2>/dev/null)
    if [ -n "$EXISTING_PID" ] && kill -0 "$EXISTING_PID" 2>/dev/null; then
        _log "PID_REUSE pid=$EXISTING_PID (window alive, DispatchSource refresh)"
        exit 0  # Window is alive; DispatchSource watcher refreshes content automatically
    fi
    _log "PID_STALE pid=$EXISTING_PID (process dead, will launch new)"
fi

# No running instance — launch new floating sticky note
if [ -f "$BINARY" ]; then
    "$BINARY" "$CONTENT_FILE" </dev/null >/dev/null 2>&1 &
    _log "LAUNCH pid=$! binary=$BINARY"
    disown $!
else
    _log "ERROR binary not found: $BINARY"
fi
